import enum
from enum import Enum


@enum.unique
class EventType(str, Enum):
    LEVEL_UP = "LEVEL_UP"
    SKILL_LEVEL_UP = "SKILL_LEVEL_UP"
    CHAMPION_KILL = "CHAMPION_KILL"
    ITEM_DESTROYED = "ITEM_DESTROYED"
    ITEM_PURCHASED = "ITEM_PURCHASED"
    WARD_PLACED = "WARD_PLACED"
    WARD_DESTROYED = "WARD_DESTROYED"
    ITEM_SOLD = "ITEM_SOLD"
    OTHER = "OTHER"
    CHAMPION_SPECIAL_KILL = "CHAMPION_SPECIAL_KILL"
    PAUSE_END = "PAUSE_END"
    GAME_END = "GAME_END"
    MINION = "MINION"
    ITEM_UNDO = "ITEM_UNDO"
    BUILDING_KILL = "BUILDING_KILL"
    TOWER = "TOWER"
